upstreamProjects:
  Mule-runtime/mule/rel/4.6.4,
  Mule-runtime/mule-oauth-client/rel/2.1.4
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
