upstreamProjects:
  Mule-runtime/mule/support/4.7.x,
  Mule-runtime/mule-oauth-client/support/2.2.x
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
