upstreamProjects:
  Mule-runtime/mule/4.6.11,
  Mule-runtime/mule-oauth-client/2.1.11
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
