upstreamProjects:
  Mule-runtime/mule/4.6.9-DRY-RUN,
  Mule-runtime/mule-oauth-client/2.1.9-DRY-RUN
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
