upstreamProjects:
  Mule-runtime/mule/4.9.0,
  Mule-runtime/mule-oauth-client/support/2.4.x
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
mavenTool: "3.9.9"
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk21:
    testJdkTool: TEMURIN-JDK21
